# Generated by Django 2.2.5 on 2021-08-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='corre',
            new_name='correo',
        ),
    ]
